In [ ]:
!tar -xzvf /content/drive/MyDrive/cifar-10-python.tar.gz

cifar-10-batches-py/
cifar-10-batches-py/data_batch_4
cifar-10-batches-py/readme.html
cifar-10-batches-py/test_batch
cifar-10-batches-py/data_batch_3
cifar-10-batches-py/batches.meta
cifar-10-batches-py/data_batch_2
cifar-10-batches-py/data_batch_5
cifar-10-batches-py/data_batch_1


In [ ]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [ ]:
batch1 = unpickle("/content/drive/MyDrive/data_batch_1")

In [ ]:
batch2 = unpickle("/content/drive/MyDrive/data_batch_2")

In [ ]:
batch3 = unpickle("/content/drive/MyDrive/data_batch_3")

In [ ]:
batch4 = unpickle("/content/drive/MyDrive/data_batch_4")

In [ ]:
batch5 = unpickle("/content/drive/MyDrive/data_batch_5")

In [ ]:
batch1

{b'batch_label': b'training batch 1 of 5',
 b'labels': [6,
  9,
  9,
  4,
  1,
  1,
  2,
  7,
  8,
  3,
  4,
  7,
  7,
  2,
  9,
  9,
  9,
  3,
  2,
  6,
  4,
  3,
  6,
  6,
  2,
  6,
  3,
  5,
  4,
  0,
  0,
  9,
  1,
  3,
  4,
  0,
  3,
  7,
  3,
  3,
  5,
  2,
  2,
  7,
  1,
  1,
  1,
  2,
  2,
  0,
  9,
  5,
  7,
  9,
  2,
  2,
  5,
  2,
  4,
  3,
  1,
  1,
  8,
  2,
  1,
  1,
  4,
  9,
  7,
  8,
  5,
  9,
  6,
  7,
  3,
  1,
  9,
  0,
  3,
  1,
  3,
  5,
  4,
  5,
  7,
  7,
  4,
  7,
  9,
  4,
  2,
  3,
  8,
  0,
  1,
  6,
  1,
  1,
  4,
  1,
  8,
  3,
  9,
  6,
  6,
  1,
  8,
  5,
  2,
  9,
  9,
  8,
  1,
  7,
  7,
  0,
  0,
  6,
  9,
  1,
  2,
  2,
  9,
  2,
  6,
  6,
  1,
  9,
  5,
  0,
  4,
  7,
  6,
  7,
  1,
  8,
  1,
  1,
  2,
  8,
  1,
  3,
  3,
  6,
  2,
  4,
  9,
  9,
  5,
  4,
  3,
  6,
  7,
  4,
  6,
  8,
  5,
  5,
  4,
  3,
  1,
  8,
  4,
  7,
  6,
  0,
  9,
  5,
  1,
  3,
  8,
  2,
  7,
  5,
  3,
  4,
  1,
  5,
  7,
  0,
  4,
  7,
  5,
  5,
  1,
  0,
  9,
  6,
  9,
 

In [ ]:
batch1[b'data']

array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144],
       [255, 253, 253, ...,  83,  83,  84],
       ...,
       [ 71,  60,  74, ...,  68,  69,  68],
       [250, 254, 211, ..., 215, 255, 254],
       [ 62,  61,  60, ..., 130, 130, 131]], dtype=uint8)

In [ ]:
batch1[b'labels']

[6,
 9,
 9,
 4,
 1,
 1,
 2,
 7,
 8,
 3,
 4,
 7,
 7,
 2,
 9,
 9,
 9,
 3,
 2,
 6,
 4,
 3,
 6,
 6,
 2,
 6,
 3,
 5,
 4,
 0,
 0,
 9,
 1,
 3,
 4,
 0,
 3,
 7,
 3,
 3,
 5,
 2,
 2,
 7,
 1,
 1,
 1,
 2,
 2,
 0,
 9,
 5,
 7,
 9,
 2,
 2,
 5,
 2,
 4,
 3,
 1,
 1,
 8,
 2,
 1,
 1,
 4,
 9,
 7,
 8,
 5,
 9,
 6,
 7,
 3,
 1,
 9,
 0,
 3,
 1,
 3,
 5,
 4,
 5,
 7,
 7,
 4,
 7,
 9,
 4,
 2,
 3,
 8,
 0,
 1,
 6,
 1,
 1,
 4,
 1,
 8,
 3,
 9,
 6,
 6,
 1,
 8,
 5,
 2,
 9,
 9,
 8,
 1,
 7,
 7,
 0,
 0,
 6,
 9,
 1,
 2,
 2,
 9,
 2,
 6,
 6,
 1,
 9,
 5,
 0,
 4,
 7,
 6,
 7,
 1,
 8,
 1,
 1,
 2,
 8,
 1,
 3,
 3,
 6,
 2,
 4,
 9,
 9,
 5,
 4,
 3,
 6,
 7,
 4,
 6,
 8,
 5,
 5,
 4,
 3,
 1,
 8,
 4,
 7,
 6,
 0,
 9,
 5,
 1,
 3,
 8,
 2,
 7,
 5,
 3,
 4,
 1,
 5,
 7,
 0,
 4,
 7,
 5,
 5,
 1,
 0,
 9,
 6,
 9,
 0,
 8,
 7,
 8,
 8,
 2,
 5,
 2,
 3,
 5,
 0,
 6,
 1,
 9,
 3,
 6,
 9,
 1,
 3,
 9,
 6,
 6,
 7,
 1,
 0,
 9,
 5,
 8,
 5,
 2,
 9,
 0,
 8,
 8,
 0,
 6,
 9,
 1,
 1,
 6,
 3,
 7,
 6,
 6,
 0,
 6,
 6,
 1,
 7,
 1,
 5,
 8,
 3,
 6,
 6,
 8,
 6,
 8,
 4,
 6,
 6,


In [ ]:
import numpy as np

In [ ]:
train_set = np.concatenate((batch1[b'data'], batch2[b'data'] , batch3[b'data'] , batch4[b'data'] , batch5[b'data']))

In [ ]:
train_set.shape

(50000, 3072)

In [ ]:
train_set_labels = np.concatenate((batch1[b'labels'], batch2[b'labels'] , batch3[b'labels'] , batch4[b'labels'] , batch5[b'labels']))

In [ ]:
train_set_labels.shape

(50000,)

In [ ]:
train_set_pics = np.concatenate((batch1[b'filenames'], batch2[b'filenames'] , batch3[b'filenames'] , batch4[b'filenames'] , batch5[b'filenames']))

In [ ]:
train_set_pics.shape

(50000,)

In [ ]:
train = train_set , train_set_labels , train_set_pics

In [ ]:
train

(array([[ 59,  43,  50, ..., 140,  84,  72],
        [154, 126, 105, ..., 139, 142, 144],
        [255, 253, 253, ...,  83,  83,  84],
        ...,
        [ 35,  40,  42, ...,  77,  66,  50],
        [189, 186, 185, ..., 169, 171, 171],
        [229, 236, 234, ..., 173, 162, 161]], dtype=uint8),
 array([6, 9, 9, ..., 9, 1, 1]),
 array([b'leptodactylus_pentadactylus_s_000004.png',
        b'camion_s_000148.png', b'tipper_truck_s_001250.png', ...,
        b'tipper_s_000416.png', b'coupe_s_001887.png',
        b'coupe_s_001616.png'], dtype='|S40'))

importing dataset

In [2]:
from tensorflow.keras.datasets import cifar10

In [3]:
import numpy as np

In [4]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

images = np.zeros((1000, 32, 32, 3))
labels = np.zeros((1000,))


for i in range(10):
    class_num = np.where(y_train == i)[0]
    np.random.shuffle(class_num)
    selected_num = class_num[:100]
    images[i*100:(i+1)*100] = x_train[selected_num]
    labels[i*100:(i+1)*100] = i




In [4]:
x_train.shape

(50000, 32, 32, 3)

In [5]:
x_train = x_train.reshape(x_train.shape[0], -1) / 255.

In [6]:
x_train.shape

(50000, 3072)

making W and B

In [6]:
w = np.random.randn(3072 ,10)

In [7]:
scores = np.dot(x_train, w)

In [8]:
b = np.random.randn(10,1)

In [9]:
s = (scores.T + b).T

In [21]:
s.shape

(50000, 10)

calculating hinge loss

In [16]:
margin = s - y_train  + 1
Li = np.maximum(0, margin)

In [17]:
Li

array([[ 0.63151566,  0.        ,  0.        , ...,  0.        ,
        20.72650179,  0.        ],
       [ 0.        , 20.94324337,  0.        , ...,  0.        ,
         8.37206945,  0.        ],
       [ 0.        ,  1.23533708,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  9.08758392,  0.        , ...,  0.        ,
        14.86744338,  0.        ],
       [ 0.        , 24.92000648,  0.        , ...,  0.        ,
        12.59954147,  0.        ],
       [ 0.        ,  0.16539856,  0.        , ...,  0.        ,
         2.1728965 ,  0.        ]])

In [20]:
L = Li.sum() / 5000
L

258.6768457783625

calculating softmax

In [23]:
softmax = (np.exp(y_train))/(s.sum())
softmax

array([[-5.1001174e-05],
       [-1.0243210e-03],
       [-1.0243210e-03],
       ...,
       [-1.0243210e-03],
       [-3.4364174e-07],
       [-3.4364174e-07]], dtype=float32)

In [24]:
softmax.shape

(50000, 1)

In [34]:
import math

In [33]:
loss_function =  -(math.log(-1 * softmax))
loss_function

14.942374642051462